version: '3'

services:
  react_native:
    build: .
    tty: true
    ports:
      - '19002:19002'
      - '19000:19000'
      - '19001:19001'
    env_file: .env
    volumes:
      - react_native:/workspace/node_modules
      - ../:/workspace:cached
volumes:
  react_native:
    driver: 'local'
# https://anytimesnotes.com/archives/246
